version: '3.3'

services:
  php:
    image: php:8.0-apache
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db/createdb.sql:/docker-entrypoint-initdb.d/appdb.sql

  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysqlrootpass
