version: '3.7'

services:

  nginx:
    image: nginx:1.25.1
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/  
    ports:
      - 8000:80
    container_name: app_nginx
    depends_on:
      - app


  app:
    build:
      args:
        user: rlusr
        uid: 1000
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    extra_hosts:
      - "messagesapp.com:127.0.0.1"
    depends_on:
      - mysql
    container_name: app

  mysql:
    image: mysql:8.0
    expose:
      - '3306'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db/createdb.sql:/docker-entrypoint-initdb.d/appdb.sql
    container_name: mysql

  




      
